name: 🚀 Deploy to hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    - name: 📂 Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ./public/
        state-name: .htautodeploycache
        server: sl11066.web.hostpoint.ch
        port: 21
        username: git@david-abderhalden.ch
        password: ${{ secrets.FTP_PASSWORD }}
